# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=100)),
                ('is_done', models.BooleanField()),
            ],
        ),
    ]
