# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
